#   _____                            ______                    _   _       _            #
#  / ____|                          |  ____|                  | | (_)     | |           #
# | (___   ___ _ ____   _____ _ __  | |__   ___ ___  ___ _ __ | |_ _  __ _| |___        #
#  \___ \ / _ \ '__\ \ / / _ \ '__| |  __| / __/ __|/ _ \ '_ \| __| |/ _` | / __|       #
#  ____) |  __/ |   \ V /  __/ |    | |____\__ \__ \  __/ | | | |_| | (_| | \__ \       #
# |_____/ \___|_|    \_/ \___|_|    |______|___/___/\___|_| |_|\__|_|\__,_|_|___/       #
#                                                                                       #
#########################################################################################

#########################################################################################
#                                   General                                             #
#########################################################################################
debug-mode: false
join-sound: true
motd-enabled: true
custom-join-message: '{RankPrefix} &d{PlayerName} &6has joined the server.'
custom-quit-message: '{RankPrefix} &d{PlayerName} &chas left the server.'
chat-format: '{RankPrefix} &d{PlayerName}&f: {Message}'
currency-name: 'Coins'
#########################################################################################
#                                Teleportation                                          #
#########################################################################################