#   _____                            ______                    _   _       _            #
#  / ____|                          |  ____|                  | | (_)     | |           #
# | (___   ___ _ ____   _____ _ __  | |__   ___ ___  ___ _ __ | |_ _  __ _| |___        #
#  \___ \ / _ \ '__\ \ / / _ \ '__| |  __| / __/ __|/ _ \ '_ \| __| |/ _` | / __|       #
#  ____) |  __/ |   \ V /  __/ |    | |____\__ \__ \  __/ | | | |_| | (_| | \__ \       #
# |_____/ \___|_|    \_/ \___|_|    |______|___/___/\___|_| |_|\__|_|\__,_|_|___/       #
#                                                                                       #
#########################################################################################
#
# config.yml is where you will change the majority of your server settings and visual
# effects such as join messages, scoreboards...etc
#
#########################################################################################
#                                   General                                             #
#########################################################################################
debug-mode: false
join-sound: true
motd-enabled: true
custom-join-message: '{RankPrefix} &d{PlayerName} &6has joined the server.'
custom-quit-message: '{RankPrefix} &d{PlayerName} &chas left the server.'
chat-format: '{RankPrefix} &d{PlayerName}&f: {Message}'
currency-name: 'Coins'
#########################################################################################
#                                  Scoreboard                                           #
#########################################################################################
#
# The scoreboards limit is currently up to 15 lines
#
Scoreboard:
  default:
    enabled: true
    title: '&4Server&cName'
    line-1: '&d&lPlayers'
    line-2: '{OnlinePlayers} Players'
    line-3: ''
    line-4: '&d&lBalance'
    line-5: '{PlayerBalance} {CurrencyName}'
    line-6: ''
    line-7: '&d&lRank'
    line-8: '{PlayerRank}'
    line-9: ''
    line-10: '&d&lStore'
    line-11: 'store.server.com'
#########################################################################################
#                                Teleportation                                          #
#########################################################################################
#
# This is where your server spawns, warps, and homes will appear.
#