#Dis is the config
#pls know default text goes here
Spawn:
join-sound: true
motd-enabled: true
custom-join-message: '&d{PlayerName} &6has joined the server.'
custom-quit-message: '&d{PlayerName} &chas left the server.'