#Dis is the config
#pls know default text goes here
debug-mode: false
join-sound: true
motd-enabled: true
custom-join-message: '&d{PlayerName} &6has joined the server.'
custom-quit-message: '&d{PlayerName} &chas left the server.'
chat-format: '{Prefix} &d{Name}&f: {Message}'