name: ServerEssentials
author: Kyle Simmonds
version: 1.0.3
main: me.kylesimmonds.serveressentials.Main
description: Server Essentials is a lightweight alternative for small to medium sized servers.
website: http://github.com/KyleYYC/ServerEssentials/

commands:
  spawn:
    description: Sends user to spawn
  setspawn:
    description: Sets spawn
  list:
    description: Lists online users
  bal:
    description: Main command for economy
  rank:
    description: Main rank command